;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="cellTag.Empty.Occupied",NewTagName="cellTag.Occupied")
+GameplayTagRedirects=(OldTagName="cellTag.Occupied.PressurePlate",NewTagName="cellTag.Floor.Occupied.PressurePlate")
+GameplayTagRedirects=(OldTagName="cellTag.Occupied.MovableBlock",NewTagName="cellTag.Floor.Occupied.MovableBlock")
+GameplayTagRedirects=(OldTagName="cellTag.Occupied.Button",NewTagName="cellTag.Floor.Occupied.Button")
+GameplayTagRedirects=(OldTagName="cellTag.Empty",NewTagName="cellTag.Floor.Unoccupied")
+GameplayTagList=(Tag="cellTag.Floor",DevComment="")
+GameplayTagList=(Tag="cellTag.Floor.Occupied",DevComment="")
+GameplayTagList=(Tag="cellTag.Floor.Occupied.Button",DevComment="")
+GameplayTagList=(Tag="cellTag.Floor.Occupied.MovableBlock",DevComment="")
+GameplayTagList=(Tag="cellTag.Floor.Occupied.PressurePlate",DevComment="")
+GameplayTagList=(Tag="cellTag.Floor.Unoccupied",DevComment="")
+GameplayTagList=(Tag="cellTag.State.Light",DevComment="")
+GameplayTagList=(Tag="cellTag.State.Shadow",DevComment="")

