;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="cellTag.Empty",DevComment="")
+GameplayTagList=(Tag="cellTag.Floor",DevComment="")
+GameplayTagList=(Tag="cellTag.Light.E",DevComment="")
+GameplayTagList=(Tag="cellTag.Light.N",DevComment="")
+GameplayTagList=(Tag="cellTag.Light.S",DevComment="")
+GameplayTagList=(Tag="cellTag.Light.W",DevComment="")
+GameplayTagList=(Tag="cellTag.Shadow",DevComment="")
+GameplayTagList=(Tag="cellTag.Shadow.1",DevComment="")
+GameplayTagList=(Tag="cellTag.Shadow.2",DevComment="")
+GameplayTagList=(Tag="cellTag.Shadow.3",DevComment="")
+GameplayTagList=(Tag="cellTag.Shadow.4",DevComment="")
+GameplayTagList=(Tag="cellTag.State.Shadow",DevComment="")
+GameplayTagList=(Tag="cellTag.Types.ShadowCaster",DevComment="")

