name: First Issue or PR Comment

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3.1.0
        with:
          issue_message: |
            # Issue Message with Markdown

            Hi, I can see this is the first issue you have created! 
            
            Any issues created are automatically added to the MS planner board, and Lopsitey (Jake - Tech Lead) is added as an assignee.
            If you assigned anyone else to the issue, that will not be overwritten. 
          pr_message: |
            # PR Message with Markdown

            Hi, I can see this is the first pull request you have created. Please assign Lopsitey (Jake - Tech Lead) so he can approve it!
            
